#spring.datasource.url=jdbc:h2:mem:employeedb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=create
#spring.jpa.show-sql=true
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


spring.datasource.url=jdbc:mysql://localhost:3306/payrolldb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=vikash@1006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect